### ISSUE TITLE
Change the ambiguous "hate speech" rule

### ISSUE THREAD

**Issue by DB503** [0-Shine-0/Goodanimemes-Rules#2]
As seen in [this](https://www.reddit.com/r/goodanimemes/comments/ijfdzx/vote_about_the_rules/g3dat8l/) comment tree, a lot of people take issues with the ambiguity of the word "hate speech" in the rules.
We need a clear definition to prevent abuse of this rule.

**Comment by Daswf852** [comment]
This issue got (presumably) closed due to the bad issue id in the PR #4

**Comment by edenprojectde** [comment]
@0-Shine-0 please reopen this issue, the merged pr doesnt fix this issue

**Comment by edenprojectde** [comment]
@Erv00

**Comment by Erv00** [comment]
@edenprojectde is right, I made a mistake, I referenced the wrong issue, this one is **not** solved yet

**Comment by edenprojectde** [comment]
> @edenprojectde is right, I made a mistake, I referenced the wrong issue, this one is **not** solved yet

Then reopen the issue 😅

**Comment by Erv00** [comment]
@worldeva closed it, they can reopen it
